import bcrypt from 'bcryptjs';

const hashedPasswordAdmin = await bcrypt.hash('Admin123!', 10);
const hashedPasswordFounder = await bcrypt.hash('Founder123!', 10);
const hashedPasswordUser = await bcrypt.hash('User123!', 10);

export const mockUsers = [
  {
    _id: 'usr_admin_1',
    name: 'StartupForge Admin',
    email: 'admin@startupforge.com',
    password: hashedPasswordAdmin,
    role: 'admin',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&q=80',
    isBlocked: false,
    isPremium: true,
    skills: ['Platform Admin', 'Management', 'Moderation'],
    bio: 'StartupForge system administrator.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_founder_1',
    name: 'Alex Rivera',
    email: 'alex.founder@techvision.io',
    password: hashedPasswordFounder,
    role: 'founder',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80',
    isBlocked: false,
    isPremium: true,
    skills: ['AI/ML', 'Product Strategy', 'React', 'Node.js'],
    bio: 'Serial entrepreneur & AI practitioner building next-gen developer tools.',
    opportunityCount: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_founder_2',
    name: 'Sarah Chen',
    email: 'sarah.founder@healthai.com',
    password: hashedPasswordFounder,
    role: 'founder',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80',
    isBlocked: false,
    isPremium: true,
    skills: ['HealthTech', 'Python', 'Biotech', 'Growth'],
    bio: 'HealthTech pioneer bridging clinical diagnostics and machine learning.',
    opportunityCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_collab_1',
    name: 'John Developer',
    email: 'dev.john@gmail.com',
    password: hashedPasswordUser,
    role: 'collaborator',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&q=80',
    isBlocked: false,
    isPremium: false,
    skills: ['React', 'Node.js', 'MongoDB', 'Tailwind CSS', 'TypeScript'],
    bio: 'Fullstack developer with 4+ years of React, Node, and Tailwind CSS experience.',
    createdAt: new Date().toISOString(),
  },
];

export const mockStartups = [
  {
    _id: 'stp_1',
    startup_name: 'NexusAI Synthetics',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
    industry: 'AI & Data Science',
    description: 'Autonomous AI agents automating complex software documentation and code refactoring.',
    funding_stage: 'Seed ($1.8M)',
    founder_email: 'alex.founder@techvision.io',
    founder_name: 'Alex Rivera',
    team_size_needed: 6,
    upvotes: 248,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_2',
    startup_name: 'BioPulse Health',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    industry: 'HealthTech',
    description: 'Wearable ECG and glucose telemetry analytics powered by preventative machine learning.',
    funding_stage: 'Pre-Seed ($650K)',
    founder_email: 'sarah.founder@healthai.com',
    founder_name: 'Sarah Chen',
    team_size_needed: 4,
    upvotes: 189,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_3',
    startup_name: 'Aura ClimateTech',
    logo: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&q=80',
    industry: 'ClimateTech',
    description: 'Decentralized carbon credit tracking and IoT environmental satellite verification.',
    funding_stage: 'Series A ($5.2M)',
    founder_email: 'alex.founder@techvision.io',
    founder_name: 'Alex Rivera',
    team_size_needed: 8,
    upvotes: 312,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_4',
    startup_name: 'FinFlow Liquidity',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&q=80',
    industry: 'FinTech',
    description: 'Algorithmic liquidity settlement protocol for global cross-border B2B payments.',
    funding_stage: 'Series A ($4.1M)',
    founder_email: 'sarah.founder@healthai.com',
    founder_name: 'Sarah Chen',
    team_size_needed: 5,
    upvotes: 275,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_5',
    startup_name: 'CyberShield Sentinel',
    logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80',
    industry: 'Cybersecurity',
    description: 'Zero-trust API security testing and real-time cloud vulnerability mitigation.',
    funding_stage: 'Seed ($2.4M)',
    founder_email: 'alex.founder@techvision.io',
    founder_name: 'Alex Rivera',
    team_size_needed: 4,
    upvotes: 195,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_6',
    startup_name: 'EduVibe Interactive',
    logo: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&q=80',
    industry: 'EdTech',
    description: 'Gamified immersive coding bootcamps powered by adaptive AI tutoring.',
    funding_stage: 'Pre-Seed ($800K)',
    founder_email: 'sarah.founder@healthai.com',
    founder_name: 'Sarah Chen',
    team_size_needed: 3,
    upvotes: 162,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_7',
    startup_name: 'RoboSwift Fulfillment',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&q=80',
    industry: 'Robotics & Automation',
    description: 'Micro-warehouse autonomous mobile robots for same-day e-commerce delivery.',
    funding_stage: 'Series A ($6.8M)',
    founder_email: 'alex.founder@techvision.io',
    founder_name: 'Alex Rivera',
    team_size_needed: 7,
    upvotes: 210,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'stp_8',
    startup_name: 'OrbitSpace Logistics',
    logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80',
    industry: 'Logistics',
    description: 'Predictive supply chain routing engine using low-Earth orbit satellite telemetry.',
    funding_stage: 'Seed ($3.1M)',
    founder_email: 'sarah.founder@healthai.com',
    founder_name: 'Sarah Chen',
    team_size_needed: 5,
    upvotes: 178,
    status: 'approved',
    createdAt: new Date().toISOString(),
  },
];

export const mockOpportunities = [
  {
    _id: 'opp_1',
    startup_id: {
      _id: 'stp_1',
      startup_name: 'NexusAI Synthetics',
      logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
      industry: 'AI & Data Science',
    },
    role_title: 'Senior Frontend Engineer (React/TS)',
    required_skills: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    work_type: 'remote',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Lead the frontend architecture for our interactive AI agent canvas UI using React, TypeScript, and WebSockets.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_2',
    startup_id: {
      _id: 'stp_1',
      startup_name: 'NexusAI Synthetics',
      logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
      industry: 'AI & Data Science',
    },
    role_title: 'Backend Systems Architect',
    required_skills: ['Node.js', 'Express', 'MongoDB', 'Redis'],
    work_type: 'hybrid',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Design robust microservices and high-throughput vector database pipelines for real-time AI indexing.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_3',
    startup_id: {
      _id: 'stp_2',
      startup_name: 'BioPulse Health',
      logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
      industry: 'HealthTech',
    },
    role_title: 'Fullstack Engineer (Health Analytics)',
    required_skills: ['React', 'Node.js', 'Python', 'Tailwind CSS'],
    work_type: 'remote',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Build real-time patient dashboards and stream BLE sensor metrics to diagnostic web consoles.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_4',
    startup_id: {
      _id: 'stp_3',
      startup_name: 'Aura ClimateTech',
      logo: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&q=80',
      industry: 'ClimateTech',
    },
    role_title: 'DevOps & Cloud Infrastructure Lead',
    required_skills: ['Docker', 'Kubernetes', 'AWS', 'Node.js'],
    work_type: 'remote',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Scale our IoT telemetry pipeline processing millions of environmental satellite metrics daily.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_5',
    startup_id: {
      _id: 'stp_4',
      startup_name: 'FinFlow Liquidity',
      logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&q=80',
      industry: 'FinTech',
    },
    role_title: 'FinTech Backend Specialist',
    required_skills: ['Node.js', 'TypeScript', 'MongoDB', 'REST APIs'],
    work_type: 'onsite',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Implement high-frequency trade reconciliation algorithms and secure banking API integrations.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_6',
    startup_id: {
      _id: 'stp_5',
      startup_name: 'CyberShield Sentinel',
      logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80',
      industry: 'Cybersecurity',
    },
    role_title: 'Security Research Engineer',
    required_skills: ['Python', 'Node.js', 'Cybersecurity', 'API Auditing'],
    work_type: 'remote',
    commitment_level: 'contract',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Develop automated penetration testing scripts to detect zero-day API token vulnerabilities.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_7',
    startup_id: {
      _id: 'stp_6',
      startup_name: 'EduVibe Interactive',
      logo: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&q=80',
      industry: 'EdTech',
    },
    role_title: 'UI/UX & Product Designer',
    required_skills: ['Figma', 'React', 'Tailwind CSS', 'User Research'],
    work_type: 'remote',
    commitment_level: 'part-time',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Craft vibrant, gamified UI interfaces for our interactive coding challenges platform.',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'opp_8',
    startup_id: {
      _id: 'stp_7',
      startup_name: 'RoboSwift Fulfillment',
      logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&q=80',
      industry: 'Robotics & Automation',
    },
    role_title: 'Robotics Fleet Software Engineer',
    required_skills: ['Python', 'C++', 'Node.js', 'System Architecture'],
    work_type: 'hybrid',
    commitment_level: 'full-time',
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Build central fleet control software steering 100+ warehouse robots in real time.',
    createdAt: new Date().toISOString(),
  },
];

export const mockApplications = [
  {
    _id: 'app_1',
    opportunity_id: 'opp_1',
    opportunity_name: 'Senior Frontend Engineer (React/TS)',
    startup_name: 'NexusAI Synthetics',
    applicant_email: 'dev.john@gmail.com',
    applicant_name: 'John Developer',
    portfolio_link: 'https://github.com/johndev-demo',
    motivation: 'I have built over 10 production React apps and love AI toolings. Excited to join NexusAI!',
    status: 'pending',
    applied_at: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const mockPayments = [
  {
    _id: 'pay_1',
    user_email: 'alex.founder@techvision.io',
    amount: 10,
    transaction_id: 'tx_demo_stripe_998124',
    payment_status: 'completed',
    paid_at: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];
